---
- hosts: localhost
  connection: local
  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "ansible-kyepair"
        instance_type: t2.micro
        security_groups:
          - default
        region: us-east-1
        aws_access_key: "{{ ec2_access_key }}"  # From vault or defined variables
        aws_secret_key: "{{ ec2_secret_key }}"  # From vault or defined variables
        image_id: "{{ item.image }}"
        network_interfaces:
          - device_index: 0
            assign_public_ip: true  # Corrected parameter to assign a public IP address
        tags:
          environment: "{{ item.name }}"
      loop:
        - { image: "ami-063d43db0594b521b", name: "manage-node-1" }  # Update AMI ID as needed
        - { image: "ami-0866a3c8686eaeeba", name: "manage-node-2" }
        - { image: "ami-0866a3c8686eaeeba", name: "manage-node-3" }