---
- hosts: all 
  become: true

  tasks:
    - name: Make sure the packages openssh and openssl are up to date
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop: 
        - openssh
        - openssl
      ignore_errors: yes

    - name: Verify Docker is installed
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes
      #when: ansible_facts['os_family'] == "RedHat"
    - name: Install Docker if not already installed in amazon linux
      ansible.builtin.yum:
        name: docker
        state: present
      when: output.failed
    - name: Install Docker if not already installed
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: output.failed
        

        